# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cmd1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(445, 334))
        self.centralwidget.setMaximumSize(QtCore.QSize(445, 334))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_feedback = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.label_feedback.setFont(font)
        self.label_feedback.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback.setObjectName("label_feedback")
        self.verticalLayout.addWidget(self.label_feedback)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_feedback_speed = QtWidgets.QLabel(self.centralwidget)
        self.label_feedback_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback_speed.setObjectName("label_feedback_speed")
        self.verticalLayout.addWidget(self.label_feedback_speed)
        self.label_status_front_steer = QtWidgets.QLabel(self.centralwidget)
        self.label_status_front_steer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_front_steer.setObjectName("label_status_front_steer")
        self.verticalLayout.addWidget(self.label_status_front_steer)
        self.label_status_rear_steer = QtWidgets.QLabel(self.centralwidget)
        self.label_status_rear_steer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_rear_steer.setObjectName("label_status_rear_steer")
        self.verticalLayout.addWidget(self.label_status_rear_steer)
        self.label_feedback_status = QtWidgets.QLabel(self.centralwidget)
        self.label_feedback_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback_status.setObjectName("label_feedback_status")
        self.verticalLayout.addWidget(self.label_feedback_status)
        self.label_feedback_loc_yawrate = QtWidgets.QLabel(self.centralwidget)
        self.label_feedback_loc_yawrate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback_loc_yawrate.setObjectName("label_feedback_loc_yawrate")
        self.verticalLayout.addWidget(self.label_feedback_loc_yawrate)
        self.label_front_offset = QtWidgets.QLabel(self.centralwidget)
        self.label_front_offset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_front_offset.setObjectName("label_front_offset")
        self.verticalLayout.addWidget(self.label_front_offset)
        self.label_rear_offset = QtWidgets.QLabel(self.centralwidget)
        self.label_rear_offset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rear_offset.setObjectName("label_rear_offset")
        self.verticalLayout.addWidget(self.label_rear_offset)
        self.label_front_offset_value = QtWidgets.QLabel(self.centralwidget)
        self.label_front_offset_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_front_offset_value.setObjectName("label_front_offset_value")
        self.verticalLayout.addWidget(self.label_front_offset_value)
        self.label_rear_offset_value = QtWidgets.QLabel(self.centralwidget)
        self.label_rear_offset_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rear_offset_value.setObjectName("label_rear_offset_value")
        self.verticalLayout.addWidget(self.label_rear_offset_value)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_param = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.label_param.setFont(font)
        self.label_param.setAlignment(QtCore.Qt.AlignCenter)
        self.label_param.setObjectName("label_param")
        self.verticalLayout_2.addWidget(self.label_param, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.line)
        self.doubleSpinBox_max_steer_angle = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_max_steer_angle.setDecimals(3)
        self.doubleSpinBox_max_steer_angle.setMaximum(90.0)
        self.doubleSpinBox_max_steer_angle.setSingleStep(1.0)
        self.doubleSpinBox_max_steer_angle.setProperty("value", 32.0)
        self.doubleSpinBox_max_steer_angle.setObjectName("doubleSpinBox_max_steer_angle")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_max_steer_angle)
        self.label_cmd_reset = QtWidgets.QLabel(self.centralwidget)
        self.label_cmd_reset.setObjectName("label_cmd_reset")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_cmd_reset)
        self.comboBox_reset = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_reset.setObjectName("comboBox_reset")
        self.comboBox_reset.addItem("")
        self.comboBox_reset.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_reset)
        self.label_front_wheel_L = QtWidgets.QLabel(self.centralwidget)
        self.label_front_wheel_L.setObjectName("label_front_wheel_L")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_front_wheel_L)
        self.doubleSpinBox_front_wheel_L = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_front_wheel_L.setMinimum(1.0)
        self.doubleSpinBox_front_wheel_L.setMaximum(10.0)
        self.doubleSpinBox_front_wheel_L.setSingleStep(0.1)
        self.doubleSpinBox_front_wheel_L.setProperty("value", 4.65)
        self.doubleSpinBox_front_wheel_L.setObjectName("doubleSpinBox_front_wheel_L")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_front_wheel_L)
        self.comboBox_plot = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_plot.setObjectName("comboBox_plot")
        self.comboBox_plot.addItem("")
        self.comboBox_plot.addItem("")
        self.comboBox_plot.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_plot)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_rear_wheel_L = QtWidgets.QLabel(self.centralwidget)
        self.label_rear_wheel_L.setObjectName("label_rear_wheel_L")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_rear_wheel_L)
        self.label_cmd_max_steer_angle = QtWidgets.QLabel(self.centralwidget)
        self.label_cmd_max_steer_angle.setObjectName("label_cmd_max_steer_angle")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_cmd_max_steer_angle)
        self.doubleSpinBox_rear_wheel_L = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rear_wheel_L.setDecimals(2)
        self.doubleSpinBox_rear_wheel_L.setMinimum(0.0)
        self.doubleSpinBox_rear_wheel_L.setMaximum(20.0)
        self.doubleSpinBox_rear_wheel_L.setSingleStep(0.1)
        self.doubleSpinBox_rear_wheel_L.setProperty("value", 4.65)
        self.doubleSpinBox_rear_wheel_L.setObjectName("doubleSpinBox_rear_wheel_L")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_rear_wheel_L)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_feedback.setText(_translate("MainWindow", "反馈"))
        self.label_feedback_speed.setText(_translate("MainWindow", "速度：0.0 km/h"))
        self.label_status_front_steer.setText(_translate("MainWindow", "前轮转角：0"))
        self.label_status_rear_steer.setText(_translate("MainWindow", "后轮转角：0"))
        self.label_feedback_status.setText(_translate("MainWindow", "状态：人工"))
        self.label_feedback_loc_yawrate.setText(_translate("MainWindow", "角度变化率：0"))
        self.label_front_offset.setText(_translate("MainWindow", "前轮零偏角度： 0"))
        self.label_rear_offset.setText(_translate("MainWindow", "后轮零偏角度：0"))
        self.label_front_offset_value.setText(_translate("MainWindow", "前轮零偏补偿值：0"))
        self.label_rear_offset_value.setText(_translate("MainWindow", "后轮零偏补偿值：0"))
        self.label_param.setText(_translate("MainWindow", "指令"))
        self.label_cmd_reset.setText(_translate("MainWindow", "复位："))
        self.comboBox_reset.setCurrentText(_translate("MainWindow", "复位"))
        self.comboBox_reset.setItemText(0, _translate("MainWindow", "复位"))
        self.comboBox_reset.setItemText(1, _translate("MainWindow", "估算"))
        self.label_front_wheel_L.setText(_translate("MainWindow", "中心至前轴轴距："))
        self.comboBox_plot.setItemText(0, _translate("MainWindow", "否"))
        self.comboBox_plot.setItemText(1, _translate("MainWindow", "是"))
        self.comboBox_plot.setItemText(2, _translate("MainWindow", "保持"))
        self.label.setText(_translate("MainWindow", "画图："))
        self.label_rear_wheel_L.setText(_translate("MainWindow", "中心至后轴距离："))
        self.label_cmd_max_steer_angle.setText(_translate("MainWindow", "最大转角："))